Add Context API for client login
pw-software-engineering/2022_f-team pull request #49
Opened 2022-04-16 21:24 UTC by jtarkowski27

2022-04-16 22:01 UTC, ZuzaTwardowska requested changes

2022-04-16 22:01 UTC, ZuzaTwardowska commented on Frontend/apps/common-components/src/Molecules/LoginForm.tsx
> +          validationFunc={(_: string) => true}
reverse changes in this file

2022-04-17 17:28 UTC, jtarkowski27 commented on Frontend/apps/client-catering-app/src/APIservices/APIservice.tsx
> +
idk, fixed

2022-04-17 17:28 UTC, jtarkowski27 commented on Frontend/apps/client-catering-app/src/pages/LoginPage.tsx
> +    if (loginData.Email.length > 32 || loginData.Email.length == 0) return false;
no clue

2022-04-17 17:28 UTC, jtarkowski27 commented on Frontend/apps/client-catering-app/src/pages/LoginPage.tsx
> +        console.log(userContext);
removed

2022-04-17 17:28 UTC, jtarkowski27 commented on Frontend/apps/common-components/src/Context/UserContext.tsx
> +            password: password,
we don't

2022-04-17 17:28 UTC, jtarkowski27 commented on Frontend/apps/common-components/src/Molecules/LoginForm.tsx
> +          validationFunc={(_: string) => true}
reversed

2022-04-18 22:50 UTC, ZuzaTwardowska commented on Frontend/apps/client-catering-app/src/Routes/PublicReoute.tsx
> +import React, { Fragment } from "react";
typo in filename

2022-04-18 22:52 UTC, ZuzaTwardowska commented on Frontend/apps/client-catering-app/src/Routes/RouteProps.tsx
> +    isAuthenticated?: boolean
can we set isAuthenticated to false by default? then we wouldn't have to check if it is null everywhere - it would be set to true during login/ register

2022-04-18 22:54 UTC, ZuzaTwardowska commented on Frontend/apps/common-components/src/Context/UserContext.tsx
> +    isAuthenticated: boolean,
are we sure we need isAuthenticated and userType?

2022-04-18 22:55 UTC, ZuzaTwardowska commented on Frontend/apps/common-components/src/Context/UserType.tsx
> +export enum UserType {
do we need that information at all? we have seperate services

2022-04-18 22:55 UTC, ZuzaTwardowska commented on Frontend/apps/common-components/src/Molecules/LoginForm.tsx
> +          validationText='Provide account password.' validationFunc={(x: string) => x.length >= 8}
prettier gone prrrt

2022-04-18 22:56 UTC, ZuzaTwardowska commented on Frontend/apps/common-components/src/Routes/PrivateRoute.tsx
> +import React, { Fragment } from "react";
are those things in cc or apps finally?

2022-04-19 00:18 UTC, ZuzaTwardowska commented on Frontend/apps/client-catering-app/src/Services/APIservice.tsx
> +  const execute = (config: ApiConfig, body: JSON, callback: Function) => {
Callback function cannot be here. Here we can pass function to parse result to our models. Maybe Try using service.result to populate userContext on useeffect in login and register page, something like:

useEffect({
       userContext?.login(service.result!);
},[service.result])

apiservice should not be responsible for setting usercontext

2022-04-19 13:32 UTC, ZuzaTwardowska approved these changes
approved after changes

2022-04-19 13:55 UTC, merged